
package ru.ifmo.se.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.6
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "EntityNotFoundById", targetNamespace = "http://soap.se.ifmo.ru/")
public class EntityNotFoundByIdException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EntityNotFoundByIdFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public EntityNotFoundByIdException(String message, EntityNotFoundByIdFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public EntityNotFoundByIdException(String message, EntityNotFoundByIdFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.ifmo.se.soap.EntityNotFoundByIdFault
     */
    public EntityNotFoundByIdFault getFaultInfo() {
        return faultInfo;
    }

}
