
package ru.ifmo.se.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.6
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "UnsupportedRsqlOperator", targetNamespace = "http://soap.se.ifmo.ru/")
public class UnsupportedRsqlOperatorException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UnsupportedRsqlOperatorFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UnsupportedRsqlOperatorException(String message, UnsupportedRsqlOperatorFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public UnsupportedRsqlOperatorException(String message, UnsupportedRsqlOperatorFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.ifmo.se.soap.UnsupportedRsqlOperatorFault
     */
    public UnsupportedRsqlOperatorFault getFaultInfo() {
        return faultInfo;
    }

}
