
package ru.ifmo.se.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.6
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HeroWebService", targetNamespace = "http://soap.se.ifmo.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HeroWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteHero", targetNamespace = "http://soap.se.ifmo.ru/", className = "ru.ifmo.se.soap.DeleteHero")
    @ResponseWrapper(localName = "deleteHeroResponse", targetNamespace = "http://soap.se.ifmo.ru/", className = "ru.ifmo.se.soap.DeleteHeroResponse")
    @Action(input = "http://soap.se.ifmo.ru/HeroWebService/deleteHeroRequest", output = "http://soap.se.ifmo.ru/HeroWebService/deleteHeroResponse")
    public boolean deleteHero(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ru.ifmo.se.soap.HeroDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addHero", targetNamespace = "http://soap.se.ifmo.ru/", className = "ru.ifmo.se.soap.AddHero")
    @ResponseWrapper(localName = "addHeroResponse", targetNamespace = "http://soap.se.ifmo.ru/", className = "ru.ifmo.se.soap.AddHeroResponse")
    @Action(input = "http://soap.se.ifmo.ru/HeroWebService/addHeroRequest", output = "http://soap.se.ifmo.ru/HeroWebService/addHeroResponse")
    public HeroDto addHero(
        @WebParam(name = "arg0", targetNamespace = "")
        HeroDto arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns ru.ifmo.se.soap.HeroDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateHero", targetNamespace = "http://soap.se.ifmo.ru/", className = "ru.ifmo.se.soap.UpdateHero")
    @ResponseWrapper(localName = "updateHeroResponse", targetNamespace = "http://soap.se.ifmo.ru/", className = "ru.ifmo.se.soap.UpdateHeroResponse")
    @Action(input = "http://soap.se.ifmo.ru/HeroWebService/updateHeroRequest", output = "http://soap.se.ifmo.ru/HeroWebService/updateHeroResponse")
    public HeroDto updateHero(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        HeroDto arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns ru.ifmo.se.soap.HeroDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findHero", targetNamespace = "http://soap.se.ifmo.ru/", className = "ru.ifmo.se.soap.FindHero")
    @ResponseWrapper(localName = "findHeroResponse", targetNamespace = "http://soap.se.ifmo.ru/", className = "ru.ifmo.se.soap.FindHeroResponse")
    @Action(input = "http://soap.se.ifmo.ru/HeroWebService/findHeroRequest", output = "http://soap.se.ifmo.ru/HeroWebService/findHeroResponse")
    public HeroDto findHero(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<ru.ifmo.se.soap.HeroDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listHeroes", targetNamespace = "http://soap.se.ifmo.ru/", className = "ru.ifmo.se.soap.ListHeroes")
    @ResponseWrapper(localName = "listHeroesResponse", targetNamespace = "http://soap.se.ifmo.ru/", className = "ru.ifmo.se.soap.ListHeroesResponse")
    @Action(input = "http://soap.se.ifmo.ru/HeroWebService/listHeroesRequest", output = "http://soap.se.ifmo.ru/HeroWebService/listHeroesResponse")
    public List<HeroDto> listHeroes(
        @WebParam(name = "arg0", targetNamespace = "")
        HeroListRequestDto arg0);

}
