
package ru.ifmo.se.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.6
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HeroWebService", targetNamespace = "http://soap.se.ifmo.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HeroWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<ru.ifmo.se.soap.HeroDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listHeroes", targetNamespace = "http://soap.se.ifmo.ru/", className = "ru.ifmo.se.soap.ListHeroes")
    @ResponseWrapper(localName = "listHeroesResponse", targetNamespace = "http://soap.se.ifmo.ru/", className = "ru.ifmo.se.soap.ListHeroesResponse")
    @Action(input = "http://soap.se.ifmo.ru/HeroWebService/listHeroesRequest", output = "http://soap.se.ifmo.ru/HeroWebService/listHeroesResponse")
    public List<HeroDto> listHeroes(
        @WebParam(name = "arg0", targetNamespace = "")
        HeroListRequestDto arg0);

}
