
package ru.ifmo.se.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.6
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HeroWebServiceService", targetNamespace = "http://soap.se.ifmo.ru/", wsdlLocation = "http://localhost:8080/HeroService?wsdl")
public class HeroWebServiceService
    extends Service
{

    private static final URL HEROWEBSERVICESERVICE_WSDL_LOCATION;
    private static final WebServiceException HEROWEBSERVICESERVICE_EXCEPTION;
    private static final QName HEROWEBSERVICESERVICE_QNAME = new QName("http://soap.se.ifmo.ru/", "HeroWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/HeroService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HEROWEBSERVICESERVICE_WSDL_LOCATION = url;
        HEROWEBSERVICESERVICE_EXCEPTION = e;
    }

    public HeroWebServiceService() {
        super(__getWsdlLocation(), HEROWEBSERVICESERVICE_QNAME);
    }

    public HeroWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HEROWEBSERVICESERVICE_QNAME, features);
    }

    public HeroWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, HEROWEBSERVICESERVICE_QNAME);
    }

    public HeroWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HEROWEBSERVICESERVICE_QNAME, features);
    }

    public HeroWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HeroWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HeroWebService
     */
    @WebEndpoint(name = "HeroWebServicePort")
    public HeroWebService getHeroWebServicePort() {
        return super.getPort(new QName("http://soap.se.ifmo.ru/", "HeroWebServicePort"), HeroWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HeroWebService
     */
    @WebEndpoint(name = "HeroWebServicePort")
    public HeroWebService getHeroWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.se.ifmo.ru/", "HeroWebServicePort"), HeroWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HEROWEBSERVICESERVICE_EXCEPTION!= null) {
            throw HEROWEBSERVICESERVICE_EXCEPTION;
        }
        return HEROWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
